### PR TITLE
Support API Blueprint Validation

### PR DESCRIPTION
**Pull request by kylef**
Adds more performance support for validation in Fury: https://github.com/apiaryio/fury.js/pull/68.

### CODE REVIEW

**Review by pksunkara — APPROVED** [review]

**Comment by pksunkara** [comment]
@kylef This is failing. Can you also change the travis to test on 4 and 6 instead of 1 and 2?

**Comment by kylef** [comment]
@pksunkara Updated.

**Comment by pksunkara** [comment]
It should still be failing. Because the errors were not because of node 2/1. It was failing on node 0.12 too.

**Comment by kylef** [comment]
@pksunkara the failures were due to `npm lint` failing due to some double quote strings which I fixed. This is now passing.

**Pull request merged**
