### PR TITLE
Fix source map support with drafter.js

### PR DESCRIPTION
**Pull request by kylef**
`generateSourceMap` is suupported on both parsers (drafter.js and protagonist), however Protagonist maintains backwards compatibility by supporting the deprecated option `exportSourcemap`. Thus we was using this deprecated option that was never supported in drafter.js.

### CODE REVIEW

**Comment by w-vi** [comment]
Why has this been closed?

**Comment by honzajavorek** [comment]
Quoting @kylef:

> I'm not too sure what the problem is, but for some reason source maps are missing via Protagonist. I tested protagonist and it works as expected on its own

> Okay I pin-pointed how to reproduce the problem, and it may cause problems on Apiary side with missing source maps

> if the option `requireBlueprintName` is passed to protagonist, protagonist doesn't give source maps

> I guess the bug was in Protagonist for long time, maybe always

**Comment by kylef** [comment]
I discovered it didn't actually solve the problem and I was still investigating. I just figured out what is happening. When protagonist is supplied the option`requireBlueprintName` along side the `exportSourcemap` or `generateSourceMap` option. Regardless of `requireBlueprintName` being true/false/undefined (https://github.com/apiaryio/fury-adapter-apib-parser/commit/e4e2e8cb6a401c2329809bf582ccc0f18d5853a2)  the source maps option would be disabled.

**Comment by w-vi** [comment]
It might be an issue in the parsing of options https://github.com/apiaryio/protagonist/blob/stable/1.x/src/options_parser.cc

**Pull request closed without merging**
