### PR TITLE
feat: Remove ast type option

### PR DESCRIPTION
**Pull request by pksunkara**

### CODE REVIEW

**Comment by pksunkara** [comment]
Needs drafter-npm new version to be released for this to be merged.

**Comment by pksunkara** [comment]
Wait, tests passed. Is the `refract` type default in drafter? In that case, we can merge this.

**Comment by pksunkara** [comment]
I can do a minor release since there's no AST support before and all this PR does is remove the type option which is by default equal to `refract` in older drafter-npm anyway.

**Comment by w-vi** [comment]
I'd wait and sync all the ast removal in go

**Comment by pksunkara** [comment]
That's what I am saying, this is not ast removal at all. It doesn't contain AST previously

**Review by kylef — APPROVED** [review]

**Pull request merged**
