### PR TITLE
Update drafter to use the drafter js to not force C++ on every build.

### PR DESCRIPTION
**Pull request by jtwebman**
We run micro services and this is a dependency in the Dredd tool. This forces a C++ on all our builds. Not sure if you will take the change but I wouldn't think building API docs would need the optimization of C++ vs javascript.

### CODE REVIEW

**Comment by kylef** [comment]
fury-adapter-apib-parser does not force C++ modules. Protagonist is an optional dependency and thus can be disabled by passing `--no-optional` to NPM install. If C++ module cannot be compiled it will be skipped automatically.

Protagonist is significantly faster at run-time and is often desired depending on the use of the parser. If for example you are using fury-adapter-apib-parser in a web service you will often want the most performant parser available. The pure JavaScript parser can be multiple times slower than Protagonist, especially for larger API Blueprint documents.

Please check out the resources in Dredd which explain this further: http://dredd.org/en/latest/installation.html#why-is-the-installation-so-slow

**Comment by jtwebman** [comment]
How do you pass the --no-optional if it is a dev dependency in your package?

**Comment by kylef** [comment]
You can do so using the following:

```shell
$ npm-install --save-dev --no-optional fury-adapter-apib-parser
```

If you have a shrinkwrap or package lock, the state of not installing Protagonist will be persistent for the next time you run `npm install`.

**Comment by jtwebman** [comment]
Will that work like this then with the dredd tool? `npm-install --save-dev --no-optional dredd`

**Comment by honzajavorek** [comment]
Yes, `npm install dredd --save-dev --no-optional` works as expected.

**Pull request closed without merging**
